#
# NOTE: Reference Framework of Protein Amino Acids' Topology
#

# NOTE: Atom compositions of amino acids
#       reference 1) Amber topologoy data $AMBERHOME/dat/leap/lib/amino19.lib
#       reference 2) Page 27 in "https://cdn.rcsb.org/wwpdb/docs/documentation/file-format/PDB_format_1992.pdf"
#       The order of atoms follows that of amber force field library.

AA_ATOMS = {
    "ALA": ["N", "H", "CA", "HA", "CB", "HB1", "HB2", "HB3", "C", "O"],
    "ARG": [
        "N",
        "H",
        "CA",
        "HA",
        "CB",
        "HB1",
        "HB2",
        "CG",
        "HG2",
        "HG3",
        "CD",
        "HD2",
        "HD3",
        "NE",
        "HE",
        "CZ",
        "NH1",
        "HH11",
        "HH12",
        "NH2",
        "HH21",
        "HH22",
        "C",
        "O",
    ],
    "ASN": [
        "N",
        "H",
        "CA",
        "HA",
        "CB",
        "HB2",
        "HB3",
        "CG",
        "OD1",
        "ND2",
        "HD21",
        "HD22",
        "C",
        "O",
    ],
    "ASP": ["N", "H", "CA", "HA", "CB", "HB2", "HB3", "CG", "OD1", "OD2", "C", "O"],
    "CYS": ["N", "H", "CA", "HA", "CB", "HB2", "HB3", "SG", "HG", "C", "O"],
    "GLN": [
        "N",
        "H",
        "CA",
        "HA",
        "CB",
        "HB2",
        "HB3",
        "CG",
        "HG2",
        "HG3",
        "CD",
        "OE1",
        "NE2",
        "C",
        "O",
    ],
    "GLU": [
        "N",
        "H",
        "CA",
        "HA",
        "CB",
        "HB2",
        "HB3",
        "CG",
        "HG2",
        "HG3",
        "CD",
        "OE1",
        "OE2",
        "C",
        "O",
    ],
    "GLY": ["N", "H", "CA", "HA", "C", "O"],
    "HID": [
        "N",
        "H",
        "CA",
        "HA",
        "CB",
        "HB2",
        "HB3",
        "CG",
        "ND1",
        "HD1",
        "CE1",
        "HE1",
        "NE2",
        "CD2",
        "HD2",
        "C",
        "O",
    ],
    "HIE": [
        "N",
        "H",
        "CA",
        "HA",
        "CB",
        "HB2",
        "HB3",
        "CG",
        "ND1",
        "CE1",
        "HE1",
        "NE2",
        "HE2",
        "CD2",
        "HD2",
        "C",
        "O",
    ],
    "HIP": [
        "N",
        "H",
        "CA",
        "HA",
        "CB",
        "HB2",
        "HB3",
        "CG",
        "ND1",
        "HD1",
        "CE1",
        "HE1",
        "NE2",
        "HE2",
        "CD2",
        "HD2",
        "C",
        "O",
    ],
    "ILE": [
        "N",
        "H",
        "CA",
        "HA",
        "CB",
        "HB",
        "CG2",
        "HG21",
        "HG22",
        "HG23",
        "CG1",
        "HG11",
        "HG12",
        "HG13",
        "CD1",
        "HD11",
        "HD12",
        "HD13",
        "C",
        "O",
    ],
    "LEU": [
        "N",
        "H",
        "CA",
        "HA",
        "CB",
        "HB2",
        "HB3",
        "CG",
        "HG",
        "CD1",
        "HD11",
        "HD12",
        "HD13",
        "CD2",
        "HD21",
        "HD22",
        "HD23",
        "C",
        "O",
    ],
    "LYS": [
        "N",
        "H",
        "CA",
        "HA",
        "CB",
        "HB2",
        "HB3",
        "CG",
        "HG2",
        "HG3",
        "CD",
        "HD2",
        "HD3",
        "CE",
        "HE2",
        "HE3",
        "NZ",
        "HZ1",
        "HZ2",
        "HZ3",
        "C",
        "O",
    ],
    "MET": [
        "N",
        "H",
        "CA",
        "HA",
        "CB",
        "HB2",
        "HB3",
        "CG",
        "HG2",
        "HG3",
        "SD",
        "CE",
        "HE1",
        "HE2",
        "HE3",
        "C",
        "O",
    ],
    "PHE": [
        "N",
        "H",
        "CA",
        "HA",
        "CB",
        "HB2",
        "HB3",
        "CG",
        "CD1",
        "HD1",
        "CE1",
        "HE1",
        "CZ",
        "HZ",
        "CE2",
        "HE2",
        "CD2",
        "HD2",
        "C",
        "O",
    ],
    "PRO": [
        "N",
        "CD",
        "HD2",
        "HD3",
        "CG",
        "HG2",
        "HG3",
        "CB",
        "HB2",
        "HB3",
        "CA",
        "HA",
        "C",
        "O",
    ],
    "SER": ["N", "H", "CA", "HA", "CB", "HB2", "HB3", "OG", "HG", "C", "O"],
    "THR": [
        "N",
        "H",
        "CA",
        "HA",
        "CB",
        "HB2",
        "HB3",
        "CG2",
        "HG21",
        "HG22",
        "HG23",
        "OG1",
        "HG1",
        "C",
        "O",
    ],
    "TRP": [
        "N",
        "CA",
        "CB",
        "HB2",
        "HB3",
        "CG",
        "CD1",
        "HD1",
        "NE1",
        "HE1",
        "CE2",
        "CZ2",
        "HZ2",
        "CH2",
        "HH2",
        "CZ3",
        "HZ3",
        "CE3",
        "HE3",
        "CD2",
        "C",
        "O",
    ],
    "TYR": [
        "N",
        "H",
        "CA",
        "HA",
        "CB",
        "HB2",
        "HB3",
        "CG",
        "CD1",
        "HD1",
        "CD2",
        "CE1",
        "CE2",
        "CZ",
        "OH",
        "C",
        "O",
    ],
    "VAL": [
        "N",
        "H",
        "CA",
        "HA",
        "CB",
        "HB",
        "CG1",
        "HG11",
        "HG12",
        "HG13",
        "CG2",
        "HG21",
        "HG22",
        "HG23",
        "C",
        "O",
    ],
}

CONNECT = {
    "ALA": [("N", "CA"), ("CA", "C"), ("C", "O"), ("CA", "CB")],
    # "ARG": [("N", "CA"), ("CA", "C"), ("C", "O"), ("CA", "CB")],
    # "ASN": [("N", "CA"), ("CA", "C"), ("C", "O"), ("CA", "CB")],
    # "ASP": [("N", "CA"), ("CA", "C"), ("C", "O"), ("CA", "CB")],
    # "CYS": [("N", "CA"), ("CA", "C"), ("C", "O"), ("CA", "CB")],
    # "GLU": [("N", "CA"), ("CA", "C"), ("C", "O"), ("CA", "CB")],
    # "GLN": [("N", "CA"), ("CA", "C"), ("C", "O"), ("CA", "CB")],
    # "GLY": [("N", "CA"), ("CA", "C"), ("C", "O")],
    # "HIS": [("N", "CA"), ("CA", "C"), ("C", "O"), ("CA", "CB")],
    # "ILE": [("N", "CA"), ("CA", "C"), ("C", "O"), ("CA", "CB")],
    # "LEU": [("N", "CA"), ("CA", "C"), ("C", "O"), ("CA", "CB")],
    # "LYS": [("N", "CA"), ("CA", "C"), ("C", "O"), ("CA", "CB")],
    # "MET": [("N", "CA"), ("CA", "C"), ("C", "O"), ("CA", "CB")],
    # "PHE": [("N", "CA"), ("CA", "C"), ("C", "O"), ("CA", "CB")],
    # "PRO": [("N", "CA"), ("CA", "C"), ("C", "O"), ("CA", "CB")],
    # "SER": [("N", "CA"), ("CA", "C"), ("C", "O"), ("CA", "CB")],
    # "THR": [("N", "CA"), ("CA", "C"), ("C", "O"), ("CA", "CB")],
    # "TRP": [("N", "CA"), ("CA", "C"), ("C", "O"), ("CA", "CB")],
    # "TYR": [("N", "CA"), ("CA", "C"), ("C", "O"), ("CA", "CB")],
    # "VAL": [("N", "CA"), ("CA", "C"), ("C", "O"), ("CA", "CB")],
}
